allowBuilds:
  "@google/genai": true
  "@prisma/engines": set this to true or false
  better-sqlite3: set this to true or false
  prisma: set this to true or false
  protobufjs: true
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
  - protobufjs
